### ISSUE TITLE
"IndexError: pop from empty list" when checking out deploy-sat-lite workflow

### ISSUE THREAD

**Issue by mirekdlugosz** [SatelliteQE/broker#17]
```
$ broker checkout --workflow deploy-sat-lite --template satellite-6.8-latest
[INFO 200618 12:59:52] Using provider AnsibleTower to checkout
Traceback (most recent call last):
  File "/home/mzalewsk/.virtualenvs/broker/bin/broker", line 11, in <module>
    load_entry_point('broker', 'console_scripts', 'broker')()
  File "/home/mzalewsk/.virtualenvs/broker/lib64/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/mzalewsk/.virtualenvs/broker/lib64/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/mzalewsk/.virtualenvs/broker/lib64/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mzalewsk/.virtualenvs/broker/lib64/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mzalewsk/.virtualenvs/broker/lib64/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/mzalewsk/.virtualenvs/broker/lib64/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/mzalewsk/sources/broker/broker/commands.py", line 56, in checkout
    broker_inst.checkout()
  File "/home/mzalewsk/sources/broker/broker/broker.py", line 55, in checkout
    host = self._act(provider, method, checkout=True)
  File "/home/mzalewsk/sources/broker/broker/broker.py", line 39, in _act
    return provider_inst.construct_host(
  File "/home/mzalewsk/sources/broker/broker/providers/ansible_tower.py", line 91, in construct_host
    job_attrs = self._merge_artifacts(
  File "/home/mzalewsk/sources/broker/broker/providers/ansible_tower.py", line 75, in _merge_artifacts
    child_obj = self.v2.jobs.get(id=child_id).results.pop()
IndexError: pop from empty list
```

That's Python 3.8.3, I'm on commit 59f5e42cbfa46713b9b808bc3cf4bd1a49e3e6e1 (which is master as of time of this writing).

In Tower I can see workflow completed successfully ($TOWER/#/workflows/3941), and in RHVM I can see new machine under my name. It seems to do the job just fine, so I don't know what his problem is.

**Comment by JacobCallahan** [comment]
@mirekdlugosz can you link me to the workflow that ran (in gchat)? I'd like to take a look at everything

**Comment by swadeley** [comment]
I have same error, can share

**Comment by mirekdlugosz** [comment]
I investigated that a little. Output modified for brevity.

This is what loop in `AnsibleTower._merge_artifacts` will be working on:
```
(Pdb) at_object.get_related('workflow_nodes')
{
    "results": [
        {
            "id": 882,
            "type": "workflow_job_node",
            "url": "/api/v2/workflow_job_nodes/882/",
            "summary_fields": {
                "job": {
                    "id": 4377,
                    "name": "satlab-tower-deploy-sat-lite-from-rhvm-02",
                    "description": "Job Template used to deploy a base 100G, 6CPU, 20G Ram sat-lite template",
                    "status": "successful",
                    "failed": false,
                    "elapsed": 891.915,
                    "type": "job"
                },
                "workflow_job": {
                    "id": 4376,
                    "name": "deploy-sat-lite",
                    "description": "Workflow to deploy sat-lite"
                },
                "unified_job_template": {
                    "id": 116,
                    "name": "satlab-tower-deploy-sat-lite-from-rhvm-02",
                    "description": "Job Template used to deploy a base 100G, 6CPU, 20G Ram sat-lite template",
                    "unified_job_type": "job"
                }
            }
        },
        {
            "id": 883,
            "type": "workflow_job_node",
            "url": "/api/v2/workflow_job_nodes/883/",
            "summary_fields": {
                "job": {
                    "id": 4388,
                    "name": "satlab-tower-deploy-set-stats-for-jenkins-automation-rhvm-02-wf",
                    "description": "Set Stats output for Jenkins and Automation to use at the end of VM Deployment",
                    "status": "successful",
                    "failed": false,
                    "elapsed": 8.917,
                    "type": "job"
                },
                "workflow_job": {
                    "id": 4376,
                    "name": "deploy-sat-lite",
                    "description": "Workflow to deploy sat-lite"
                },
                "unified_job_template": {
                    "id": 85,
                    "name": "satlab-tower-deploy-set-stats-for-jenkins-automation-rhvm-02-wf",
                    "description": "Set Stats output for Jenkins and Automation to use at the end of VM Deployment",
                    "unified_job_type": "job"
                }
            }
        }
    ]
}
```
There are two jobs: 4377 and 4388. Let's look at them:
```
(Pdb) self.v2.workflow_jobs.get(id=4377)
{
    "count": 0,
    "next": null,
    "previous": null,
    "results": []
}
(Pdb) self.v2.jobs.get(id=4388)
{
    "count": 1,
    "next": null,
    "previous": null,
    "results": [
    ]
}
```
And looking at API explorer on ansible tower ($TOWER_URL/api/v2/jobs/?page=12):
```
{
    "results": [
        {
            "id": 4370,
        },
        {
            "id": 4372,
        },
        {
            "id": 4373,
        },
        {
            "id": 4388,
        }
    ]
}
```

There's visible gap between 4373 and 4388. Out of two related jobs, only one is displayed in jobs list, which suggest that only one is visible.

I would assume this is permission setup issue on Tower.

**Comment by JacobCallahan** [comment]
Correct, we've come to the same conclusion and I've confirmed in our tower instance. For some reason these jobs have incorrect permissions compared to the ones spawned by deploy-base-rhel.
We'll get this resolved on our tower config.
