### ISSUE TITLE
'AnsibleTower' object has no attribute 'inventory'

### ISSUE THREAD

**Issue by LadislavVasina1** [SatelliteQE/broker#199]
While running this command: `broker extend --all --new-expire-time '2026-12-31 23:59'` I get this error:

```
Traceback (most recent call last):
      File "/home/lvasina/.virtualenvs/Broker/lib/python3.11/site-packages/broker/commands.py", line 42, in __call__
        return self.main(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/lvasina/.virtualenvs/Broker/lib/python3.11/site-packages/click/core.py", line 1055, in main
        rv = self.invoke(ctx)
             ^^^^^^^^^^^^^^^^
      File "/home/lvasina/.virtualenvs/Broker/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/lvasina/.virtualenvs/Broker/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
        return ctx.invoke(self.callback, **ctx.params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/lvasina/.virtualenvs/Broker/lib/python3.11/site-packages/click/core.py", line 760, in invoke
        return __callback(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/lvasina/.virtualenvs/Broker/lib/python3.11/site-packages/broker/commands.py", line 25, in wrapper
        retval = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
      File "/home/lvasina/.virtualenvs/Broker/lib/python3.11/site-packages/broker/commands.py", line 319, in extend
        broker_inst.extend(sequential=sequential)
      File "/home/lvasina/.virtualenvs/Broker/lib/python3.11/site-packages/broker/broker.py", line 291, in extend
        _host = completed.result()
                ^^^^^^^^^^^^^^^^^^
      File "/usr/lib64/python3.11/concurrent/futures/_base.py", line 449, in result
        return self.__get_result()
               ^^^^^^^^^^^^^^^^^^^
      File "/usr/lib64/python3.11/concurrent/futures/_base.py", line 401, in __get_result
        raise self._exception
      File "/usr/lib64/python3.11/concurrent/futures/thread.py", line 58, in run
        result = self.fn(*self.args, **self.kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/lvasina/.virtualenvs/Broker/lib/python3.11/site-packages/broker/broker.py", line 253, in _extend
        self._act(provider, "extend_vm", checkout=False)
      File "/home/lvasina/.virtualenvs/Broker/lib/python3.11/site-packages/broker/broker.py", line 117, in _act
        result = method_obj(**self._kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/lvasina/.virtualenvs/Broker/lib/python3.11/site-packages/broker/providers/ansible_tower.py", line 553, in extend_vm
        del self.inventory  # clear the cached value
            ^^^^^^^^^^^^^^
    AttributeError: 'AnsibleTower' object has no attribute 'inventory'
[E 230316 09:33:44 exceptions:12] BrokerError: 'AnsibleTower' object has no attribute 'inventory'
```

**Comment by LadislavVasina1** [comment]
Additional info:
This is happening if I want to checkin VM deployed on `rhv` whilst having `osp` set on default in  `broker_settings.yaml`. If I set `rhv` to default in `broker_settings.yaml` this error is not appearing anymore.
